service: athletefuel-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TABLE_NAME: AthleteFuel

plugins:
  - serverless-offline

functions:

  register:
    handler: lambdas/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: lambdas/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  profile:
    handler: lambdas/auth/profile.handler
    events:
      - http:
          path: auth/profile
          method: get
          cors: true

  updateProfile:
    handler: lambdas/auth/updateProfile.handler
    events:
      - http:
          path: auth/profile
          method: put
          cors: true

  forgotPassword:
    handler: lambdas/auth/forgotPassword.handler
    events:
      - http:
          path: auth/forgot-password
          method: post
          cors: true

  resetPassword:
    handler: lambdas/auth/resetPassword.handler
    events:
      - http:
          path: auth/reset-password
          method: post
          cors: true

  createWorkout:
    handler: lambdas/workouts/createWorkout.handler
    events:
      - http:
          path: workouts/create
          method: post
          cors: true

  getWorkouts:
    handler: lambdas/workouts/getWorkouts.handler
    events:
      - http:
          path: workouts/list
          method: get
          cors: true

  createSupplement:
    handler: lambdas/supplements/createSupplement.handler
    events:
      - http:
          path: supplements/create
          method: post
          cors: true

  getSupplements:
    handler: lambdas/supplements/getSupplements.handler
    events:
      - http:
          path: supplements/list
          method: get
          cors: true

resources:
  Resources:
    AthleteFuelTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AthleteFuel
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH