service: athletefuel-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TABLE_NAME: AthleteFuel
    RESEND_API_KEY: re_PrNZVTbk_AC44k6eQ1yeJDBQAEQyK8Ezy

plugins:
  - serverless-offline

functions:

  register:
    handler: lambdas/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: lambdas/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  profile:
    handler: lambdas/auth/profile.handler
    events:
      - http:
          path: auth/profile
          method: get
          cors: true

  updateProfile:
    handler: lambdas/auth/updateProfile.handler
    events:
      - http:
          path: auth/profile
          method: put
          cors: true

  forgotPassword:
    handler: lambdas/auth/forgotPassword.handler
    events:
      - http:
          path: auth/forgot-password
          method: post
          cors: true

  resetPassword:
    handler: lambdas/auth/resetPassword.handler
    events:
      - http:
          path: auth/reset-password
          method: post
          cors: true

  createWorkout:
    handler: lambdas/workouts/createWorkout.handler
    events:
      - http:
          path: workouts/create
          method: post
          cors: true

  getWorkouts:
    handler: lambdas/workouts/getWorkouts.handler
    events:
      - http:
          path: workouts/list
          method: get
          cors: true

  updateWorkout:
    handler: lambdas/workouts/updateWorkout.handler
    events:
      - http:
          path: workouts/update/{id}
          method: put
          cors: true

  deleteWorkout:
    handler: lambdas/workouts/deleteWorkout.handler
    events:
      - http:
          path: workouts/delete/{id}
          method: delete
          cors: true

  createSession:
    handler: lambdas/workouts/createSession.handler
    events:
      - http:
          path: workouts/sessions
          method: post
          cors: true

  getSessions:
    handler: lambdas/workouts/getSessions.handler
    events:
      - http:
          path: workouts/sessions
          method: get
          cors: true

  deleteSession:
    handler: lambdas/workouts/deleteSession.handler
    events:
      - http:
          path: workouts/sessions/{id}
          method: delete
          cors: true

  updateSession:
    handler: lambdas/workouts/updateSession.handler
    events:
      - http:
          path: workouts/sessions/{id}
          method: put
          cors: true

  createSupplement:
    handler: lambdas/supplements/createSupplement.handler
    events:
      - http:
          path: supplements/create
          method: post
          cors: true

  getSupplements:
    handler: lambdas/supplements/getSupplements.handler
    events:
      - http:
          path: supplements/list
          method: get
          cors: true

  updateSupplement:
    handler: lambdas/supplements/updateSupplement.handler
    events:
      - http:
          path: supplements/update/{id}
          method: put
          cors: true

  deleteSupplement:
    handler: lambdas/supplements/deleteSupplement.handler
    events:
      - http:
          path: supplements/delete/{id}
          method: delete
          cors: true

  scheduleIntake:
    handler: lambdas/supplements/scheduleIntake.handler
    events:
      - http:
          path: supplements/schedule
          method: post
          cors: true

  getScheduledIntakes:
    handler: lambdas/supplements/getScheduledIntakes.handler
    events:
      - http:
          path: supplements/schedule
          method: get
          cors: true

  deleteScheduledIntake:
    handler: lambdas/supplements/deleteScheduledIntake.handler
    events:
      - http:
          path: supplements/schedule/{id}
          method: delete
          cors: true

  updateScheduledIntake:
    handler: lambdas/supplements/updateScheduledIntake.handler
    events:
      - http:
          path: supplements/schedule/{id}
          method: put
          cors: true

resources:
  Resources:
    AthleteFuelTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AthleteFuel
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
